# Combine all participant data into a big csv

In [42]:
import glob
import numpy as np
import pandas as pd

In [59]:
# reading the files without the extra 'unnamed col'
import glob
import numpy as np
import pandas as pd

path = 'C:/Users/evach/Documents/MSc/Diss_data/3_set_baseline/All/Human_NASA/'


files = glob.glob(path+'/*.csv')
p_lst = (pd.read_csv(i, index_col=[0]) for i in files)

for i in range(0, len([p_lst])):
    combine = pd.concat(p_lst)
combine = combine.iloc[:,:12]
combine
# combine.to_csv(path +'combined_all'+'.csv')

Test name   Sets     0     1     2     3     4     5     6     7  \
0      Mental demand  set 1   0.0   5.0  10.0  15.0   0.0   5.0  10.0   5.0   
1      Mental demand  set 2  15.0  10.0  10.0   5.0   5.0   5.0   5.0   5.0   
2      Mental demand  set 3  20.0  15.0   5.0  20.0  30.0  10.0  15.0  15.0   
3   Physical demand   set 1  30.0  40.0  45.0  45.0  45.0  45.0  50.0  50.0   
4   Physical demand   set 2  65.0  65.0  70.0  70.0  70.0  75.0  70.0  80.0   
..               ...    ...   ...   ...   ...   ...   ...   ...   ...   ...   
85               NaN  set 3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
86               NaN  set 3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
87               NaN  set 3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
88               NaN  set 3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
89               NaN  set 3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

       8     9  
0    5.0   5.0  
1    5.0   5.0  
2   15.0  10.0  
3   45.0  45.0  
4   85.0  90.0  
..   ...   ...  
85   NaN   NaN  
86   NaN   NaN  
87   NaN   NaN  
88   NaN   NaN  
89   NaN   NaN  

[654 rows x 12 columns]

In [126]:
path = 'C:/Users/evach/Documents/MSc/Diss_data/3_set_baseline/All/Human_NASA/combined_all.csv'


In [127]:
combine = pd.read_csv(path, index_col =[0])
combine

Test name   Sets   0   1   2   3   4   5   6   7   8   9
0      Mental demand  set 1   0   5  10  15   0   5  10   5   5   5
1      Mental demand  set 2  15  10  10   5   5   5   5   5   5   5
2      Mental demand  set 3  20  15   5  20  30  10  15  15  15  10
3   Physical demand   set 1  30  40  45  45  45  45  50  50  45  45
4   Physical demand   set 2  65  65  70  70  70  75  70  80  85  90
..               ...    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
19        Motivation  set 2  20  30  25  20  15  15  10  10   5   5
20        Motivation  set 3  60  55  45  35  30  20  15  15   5   0
21         bnb score  set 1  79  82  79  80  73  79  74  76  77  78
22         bnb score  set 2  68  69  57  69  67  71  71  69  72  72
23         bnb score  set 3  58  65  63  66  66  61  67  65  63  69

[96 rows x 12 columns]

# A random file that gives the name list

In [54]:

path_ignore = 'C:/Users/evach/Documents/MSc/Diss_data/3_set_baseline/Weighted 4 out of 4/01_Martina/com'
# path = 'C:/Users/evach/Documents/MSc/Diss_data/3_set_baseline/Latency/00_Dong/com/TLX/'
csv_files = glob.glob(path_ignore +'/*.csv')
t_df_lst = [pd.read_csv(i) for i in csv_files]
tlx_1 = t_df_lst[0]
tlx_1

Test  T_1  T_2  T_3  T_4  T_5  T_6  T_7  \
0                        Mental demand   30   50   50   60   50   40   50   
1                     Physical demand    30   40   50   50   60   50   60   
2  Temporal performance ( how hurried)   30   40   40   40   40   40   40   
3                          Performance   70   50   60   70   80   80   60   
4                              Effort    90   90   90   90   90   90   90   
5                          Frustration    0   50   50   60   50   40   50   
6                           Motivation   80   80   80   80   80   80   80   
7                            bnb score   14    9   12   14   16   18   14   

   T_8  T_9  T_10  
0   50   40    50  
1   60   70    79  
2   40   40    40  
3   70   80    70  
4   90   90    90  
5   40   40    50  
6   80   80    80  
7   13   19    16

# Get name-based data, each combined into (set 1, set 2, set 3)

# 
find_idx ----> return a list of T/F array 
set_loc  ----> for each test_name ('Mental','Physical' ...) use find_idx() to get their index location. Then access the the data frame of such location, creating a name-based dataframe

The name based data frame were then convert into its own set category
- mental demand (set 1, set 2, set 3)

In [128]:
# return the indices of the desired NASA test name, as pd.Index() return an array of T/F
# we return the indice when the condition = true
num_sets = 3
# converting the T/F array to a list of index which will then be used in set_loc
def find_idx(data):
    ls =[]
    for i in range(0,len(data)):
        if data[i]:
            ls.append(i)
    return ls
        

def set_loc(test_name):
    tst_name = pd.Index(combine['Test name']).get_loc(test_name) # get the location of desired set name, e.g. 'Mental command
    name_idx = find_idx(tst_name)
    name_frame = combine.iloc[name_idx,:12]
    name_frame.reset_index(drop=True, inplace = True)

    sets = ['set 1', 'set 2', 'set 3']
    set_frame = [[] for i in range(0,num_sets)]
    for i in range(0, len(sets)):
        set_name  = pd.Index(name_frame['Sets']).get_loc(sets[i])
        set_idx = find_idx(set_name)
        set_frame[i] = name_frame.iloc[set_idx,:12]
        set_frame[i].reset_index(drop = True, inplace = True)

    return set_frame
    
set_loc('Physical demand ')
# set_loc('Mental demand')

[          Test name   Sets   0   1   2   3   4   5   6   7   8   9
 0  Physical demand   set 1  30  40  45  45  45  45  50  50  45  45
 1  Physical demand   set 1  30  30  35  40  40  45  40  50  40  30
 2  Physical demand   set 1  60  50  53  55  40  45  46  45  40  35
 3  Physical demand   set 1   5  20  30  30  40  45  40  45  35  35,
           Test name   Sets   0   1   2   3   4   5   6   7   8   9
 0  Physical demand   set 2  65  65  70  70  70  75  70  80  85  90
 1  Physical demand   set 2  50  55  55  60  60  60  60  65  65  65
 2  Physical demand   set 2  60  80  85  85  85  85  90  95  90  95
 3  Physical demand   set 2  10  15  20  20  50  55  55  65  75  80,
           Test name   Sets   0    1    2    3    4    5    6    7    8    9
 0  Physical demand   set 3  50   60   70   80   85   85   90  100  100  100
 1  Physical demand   set 3  60   75   75   80   80   85   85   88   90   80
 2  Physical demand   set 3  90  100  100  100  100  100  100  100  100  100
 3  Physic

In [130]:
# mental_d = set_loc('Mental demand')

# This function provide the according name as well as set separation of the data
# data[0] is mental demand with all 3 sets of data, 
# data[0][0] = set 1
# data[0][1] = set 2
def nasa_name_set():
    names = pd.Index(tlx_1['Test'])
    data = [[] for i in range(0, len(names))]
    for i in range(0,len(names)):
        data[i] = set_loc(names[i])
    return data


def plt_com(data_name= nasa_name_set()):
    
    data = [[] for i in range(0, len(data_name))]
    
    for i in range(0, len(data_name)):
        s1_data = np.asarray(data_name[i][0].iloc[:9,2:]).flatten()
        s2_data = np.asarray(data_name[i][1].iloc[:9,2:]).flatten()
        s3_data = np.asarray(data_name[i][2].iloc[:9,2:]).flatten()
        data[i] = [s1_data,s2_data,s3_data]

    return data
plt_com()

[[array([ 0,  5, 10, 15,  0,  5, 10,  5,  5,  5, 15, 15, 15, 15, 15, 15, 10,
         15, 10, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 20, 30, 20,
         20, 20, 20, 25, 15, 10], dtype=int64),
  array([15, 10, 10,  5,  5,  5,  5,  5,  5,  5, 10, 10, 10, 10, 10, 10, 10,
          5,  5, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 30, 40, 30,
         30, 30, 35, 35, 45, 35], dtype=int64),
  array([20, 15,  5, 20, 30, 10, 15, 15, 15, 10, 30, 30, 30, 40, 35, 45, 30,
         35, 30, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 20, 20, 15,
         15,  5, 10, 10, 15, 15], dtype=int64)],
 [array([30, 40, 45, 45, 45, 45, 50, 50, 45, 45, 30, 30, 35, 40, 40, 45, 40,
         50, 40, 30, 60, 50, 53, 55, 40, 45, 46, 45, 40, 35,  5, 20, 30, 30,
         40, 45, 40, 45, 35, 35], dtype=int64),
  array([65, 65, 70, 70, 70, 75, 70, 80, 85, 90, 50, 55, 55, 60, 60, 60, 60,
         65, 65, 65, 60, 80, 85, 85, 85, 85, 90, 95, 90, 95, 10, 15, 20, 20,
         50, 55, 55, 65, 75, 80], dty

## Saving the flattened array for ANOVA testing

In [131]:
data_all = plt_com()
dic = {}
keys = pd.Index(tlx_1['Test'])
val = data_all

for i in range(0,len(keys)):
    dic[keys[i]] = val[i]


# returns 8 data frame - one for a nasa question
# each data frame has 2 columns: 
- one for 'sets', which includes sorted (set 1, set 2, set 3) information
- one for data, is the corresponding data to each set of the question
note this data had already combined all particitpants' info

In [132]:
dic

{'Mental demand': [array([ 0,  5, 10, 15,  0,  5, 10,  5,  5,  5, 15, 15, 15, 15, 15, 15, 10,
         15, 10, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 20, 30, 20,
         20, 20, 20, 25, 15, 10], dtype=int64),
  array([15, 10, 10,  5,  5,  5,  5,  5,  5,  5, 10, 10, 10, 10, 10, 10, 10,
          5,  5, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 30, 40, 30,
         30, 30, 35, 35, 45, 35], dtype=int64),
  array([20, 15,  5, 20, 30, 10, 15, 15, 15, 10, 30, 30, 30, 40, 35, 45, 30,
         35, 30, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 20, 20, 15,
         15,  5, 10, 10, 15, 15], dtype=int64)],
 'Physical demand ': [array([30, 40, 45, 45, 45, 45, 50, 50, 45, 45, 30, 30, 35, 40, 40, 45, 40,
         50, 40, 30, 60, 50, 53, 55, 40, 45, 46, 45, 40, 35,  5, 20, 30, 30,
         40, 45, 40, 45, 35, 35], dtype=int64),
  array([65, 65, 70, 70, 70, 75, 70, 80, 85, 90, 50, 55, 55, 60, 60, 60, 60,
         65, 65, 65, 60, 80, 85, 85, 85, 85, 90, 95, 90, 95, 10, 15, 20, 20,


In [133]:
name_lst= pd.Index(tlx_1['Test'])
a = pd.DataFrame(dic).loc[0,name_lst[7]]
len(a)

40

In [134]:
name_lst[1]

'Physical demand '

In [135]:
idx_s1 = pd.Series(['set 1' for j in range(0,len(a))])
len(idx_s1)

40

In [136]:
# initial frame will return a data frame with 3 rows, each representing each set
# ----> has 8 columns, one for each nasa qus
# all data within has been previously flattened already

# goal: reshape the data frame into
# ----> keep the 8 columns, but unpack the array within each element
# ----> so turn set 1 into a pd series then concat it with set 2 & 3

def nasa_final(dic = dic, name_lst= pd.Index(tlx_1['Test'])):
    initial_frame = pd.DataFrame(dic)
    
    s1_data = [[] for i in range(len(name_lst))]
    s2_data = [[] for i in range(len(name_lst))]
    s3_data = [[] for i in range(len(name_lst))]

    set_1_final = [[] for i in range(0,len(name_lst))]
    set_2_final = [[] for i in range(0,len(name_lst))]
    set_3_final = [[] for i in range(0,len(name_lst))]
    final_col = [[] for i in range(0,len(name_lst))]
    
    for i in range(0,len(name_lst)):
        s1_data[i] = pd.Series(initial_frame.loc[0,name_lst[i]])
        s2_data[i] = pd.Series(initial_frame.loc[1,name_lst[i]])
        s3_data[i] = pd.Series(initial_frame.loc[2,name_lst[i]])

        # provide a column with set information as index
        idx_s1 = pd.Series(['set 1' for j in range(0,len(s1_data[0]))])
        idx_s2 = pd.Series(['set 2' for j in range(0,len(s2_data[0]))])
        idx_s3 = pd.Series(['set 3' for j in range(0,len(s3_data[0]))])

        print(s1_data[i])
        # print(idx_s1)
        s1_data[i].index = idx_s1
        s2_data[i].index = idx_s2
        s3_data[i].index = idx_s3

        # print(s1_data[i])

        set_1_final[i] = s1_data[i].reset_index(drop = False)
        set_2_final[i] = s2_data[i].reset_index(drop = False)
        set_3_final[i] = s3_data[i].reset_index(drop = False)

        set_1_final[i].columns =['Sets',name_lst[i]]
        set_2_final[i].columns =['Sets',name_lst[i]]
        set_3_final[i].columns =['Sets',name_lst[i]]

        #
        final_col[i] = pd.concat([set_1_final[i], set_2_final[i], set_3_final[i]], axis = 0)
        
        # final_col[i] = pd.concat([s1_data[i], s2_data[i], s3_data[i]], axis = 0)

    return final_col

Concating the 8 questions together into one big data frame

In [138]:
# a = final column
path = 'C:/Users/evach/Documents/MSc/Diss_data/3_set_baseline/All/Human_NASA/'

def nasa_combine (a = nasa_final()):
    for i in range(1,len(pd.Index(tlx_1['Test']))):
        a[i].drop('Sets',axis=1,inplace = True)
    end_nasa = pd.concat([a[0],a[1],a[2],a[3], a[4], a[5], a[6],a[7]], axis = 1)

    end_nasa.to_csv(path+'manova friendly'+'.csv')

nasa_combine()

0      0
1      5
2     10
3     15
4      0
5      5
6     10
7      5
8      5
9      5
10    15
11    15
12    15
13    15
14    15
15    15
16    10
17    15
18    10
19    10
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30    10
31    20
32    30
33    20
34    20
35    20
36    20
37    25
38    15
39    10
dtype: int64
0     30
1     40
2     45
3     45
4     45
5     45
6     50
7     50
8     45
9     45
10    30
11    30
12    35
13    40
14    40
15    45
16    40
17    50
18    40
19    30
20    60
21    50
22    53
23    55
24    40
25    45
26    46
27    45
28    40
29    35
30     5
31    20
32    30
33    30
34    40
35    45
36    40
37    45
38    35
39    35
dtype: int64
0     60
1     70
2     70
3     65
4     60
5     55
6     70
7     70
8     65
9     65
10    20
11    25
12    20
13    25
14    25
15    30
16    30
17    30
18    20
19    10
20    70
21    70
22    71
23    60
24    60
25    65
26    55
27    40
28